FROM php:7.4-fpm-alpine

    # Install PHP-FPM Extensions, Nginx, and Supervisord
    RUN docker-php-ext-install bcmath opcache pdo_mysql \
        && apk add --no-cache nginx supervisor

    # Copy Configuration files
    # Start with things least likely to change
    COPY ./docker/supervisord/global/supervisord.conf /etc/supervisord.conf
    COPY ./docker/nginx/global/nginx.conf /etc/nginx/nginx.conf
    COPY ./docker/nginx/global/conf.d/* /etc/nginx/conf.d
    COPY ./docker/php-fpm/development/conf.d/* /usr/local/etc/php/conf.d

    # Override Working Directory
    RUN rm -rf /var/www/html
    WORKDIR /var/www/app

    # Override Entrypoint
    ENTRYPOINT []

    # Add a new command
    CMD [ "/usr/bin/supervisord" , "-c", "/etc/supervisord.conf" ]
