version: '3.2'

services:
    #
    # MySQL handles the database side of things.
    #
    mysql:
        environment:
            - MYSQL_DATABASE=laravel
            - MYSQL_ROOT_PASSWORD=root
        image: mysql:8.0.21
        ports:
            - 3306:3306
        volumes:
            - ./.data/mysql:/var/lib/mysql

    #
    # The webserver handles serving up static assets and processing PHP files.
    #
    webserver:
        build:
            context: .
            dockerfile: Dockerfile.dev
        depends_on: 
            - mysql
        environment: 
            - DB_CONNECTION=mysql
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_USERNAME=root
            - DB_PASSWORD=root
        ports:
            - 80:80
        volumes:
            - ./src:/var/www/app

    #
    # This workspace lets you run artisan and npm commands.
    #
    workspace:
        # Create a Laravel project if the source directory is empty
        command: /bin/sh -c 'if [ ! "$$(ls -A /var/www/app | grep -v -i git)" ]; then composer create-project laravel/laravel /var/www/app; fi && php -a'
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_USERNAME=root
            - DB_PASSWORD=root
        image: anterisdev/php-workspace:sha-2f305bd
        tty: true
        volumes:
            - ./src:/var/www/app
